apiVersion: apps/v1
kind: Deployment
metadata:
  name: letsgetlunch
  namespace: lunch
  labels:
    app: letsgetlunch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: letsgetlunch
  template:
    metadata:
      labels:
        app: letsgetlunch
    spec:
      containers:
        - name: letsgetlunch
          image: paulgmiller/letsgetlunch:2f3b9d0
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: PORT
              value: "8080"
            - name: DATABASE_URL
              value: "postgresql://root@cockroachdb-public.cockroach.svc.cluster.local:26257/lunch?sslmode=disable"
---
apiVersion: v1
kind: Service
metadata:
  name: letsgetlunch
  namespace: lunch
  labels:
    app: letsgetlunch
spec:
  selector:
    app: letsgetlunch
  ports:
    - name: http
      port: 80
      targetPort: http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: letsgetlunch
spec:
  rules:
    - host: lunch.northbriton.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: letsgetlunch
                port:
                  name: http
